@echo off
echo Starting CentralPerk Rewards Microservices locally...

echo Starting Rewards API Gateway...
start "Rewards API Gateway" cmd /k "cd apps\rewards-api-gateway && npx tsx src/server.ts"

echo Starting Member Service...
start "Member Service" cmd /k "cd apps\member-service && npx tsx src/server.ts"

echo Starting Segment Service...
start "Segment Service" cmd /k "cd apps\segment-service && npx tsx src/server.ts"

echo Starting Campaign Service...
start "Campaign Service" cmd /k "cd apps\campaign-service && npx tsx src/server.ts"

echo Starting Notification Service...
start "Rewards Notification Service" cmd /k "cd apps\rewards-notification-service && npx tsx src/server.ts"

echo Starting Reward Service...
start "Reward Service" cmd /k "cd apps\reward-service && npx tsx src/server.ts"

echo Starting Points Engine...
start "Points Engine" cmd /k "cd apps\points-engine && npx tsx src/server.ts"

echo All Rewards services have been launched!
