@echo off
echo Starting OOS System 1 Microservices locally...

echo Starting OOS API Gateway...
start "OOS API Gateway" cmd /k "cd apps\oos-api-gateway && npm run build && npm run start:prod"

echo Starting OOS Auth Service...
start "OOS Auth Service" cmd /k "cd apps\oos-auth-service && npm run build && npm run start:prod"

echo Starting Cart Service...
start "Cart Service" cmd /k "cd apps\cart-service && npm run build && npm run start:prod"

echo Starting Catalog Service...
start "Catalog Service" cmd /k "cd apps\catalog-service && npm run build && npm run start:prod"

echo Starting Delivery Service...
start "Delivery Service" cmd /k "cd apps\delivery-service && npm run build && npm run start:prod"

echo Starting Order Service...
start "Order Service" cmd /k "cd apps\order-service && npm run build && npm run start:prod"

echo Starting Promo Service...
start "Promo Service" cmd /k "cd apps\promo-service && npm run build && npm run start:prod"

echo All OOS services have been launched!
